version: '3'

services:

  sheep-server:
    container_name: sheep_sheep-server_1
    build:
      context: backend
      dockerfile: backend/Dockerfile_server
    command: applications/run-sheep-server
    ports:
     - "34568:34568"
    networks:
     - sheep_nw

  sheep-frontend:
    container_name: sheep_sheep-frontend_1
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    ports:
    - "5000:5000"
    environment:
    - FLASK_CONFIGURATION=default
    - SERVER_URL_BASE=http://sheep_sheep-server_1:34568/SheepServer
    depends_on:
    - sheep-server
    networks:
    - sheep_nw

  sheep-notebook:
    container_name: sheep_sheep-notebook_1
    build:
      context: frontend
      dockerfile: Dockerfile.notebook
    depends_on:
    - sheep-server
    ports:
    - "8888:8888"
    environment:
    - SHEEP_HOME=/frontend
    - SERVER_URL_BASE=http://sheep_sheep-server_1:34568/SheepServer
    networks:
    - sheep_nw

networks:
  sheep_nw:
    driver: bridge
