FROM sheep_base as sheep_server

ENV LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:/PALISADE/bin/lib:/PALISADE/third-party/lib"
ENV LIBRARY_PATH "${LIBRARY_PATH}:/PALISADE/bin/lib"

ENV CMAKE_LIBRARY_PATH "/usr/local/lib:/PALISADE/bin/lib/:/PALISADE/third-party/lib"
ENV CMAKE_INCLUDE_PATH "/PALISADE/src/pke/lib/:/PALISADE/src/:/PALISADE/src/core/lib/:/PALISADE/third-party/include/"

ENV CPLUS_INCLUDE_PATH "/PALISADE/src/pke/lib/:/PALISADE/src/:/PALISADE/src/core/lib/:/PALISADE/third-party/include/"


ADD applications SHEEP/backend/applications
ADD cmake SHEEP/backend/cmake
ADD CMakeLists.txt SHEEP/backend/CMakeLists.txt
ADD include SHEEP/backend/include
ADD src SHEEP/backend/src
ADD tests SHEEP/backend/tests

RUN rm -fr SHEEP/backend/build; mkdir SHEEP/backend/build

RUN cd SHEEP/backend/build; export CC=gcc-9; export CXX=g++-9; cmake ../

RUN cd SHEEP/backend/build; make VERBOSE=1 run-sheep-server


WORKDIR SHEEP/backend/build

EXPOSE 34568

CMD ["bin/run-sheep-server"]
